-- schema.sql
-- Setup schema and dummy data for PL/SQL Control Structures exercise

-- Drop existing tables to ensure clean re-runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Loans';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Customers';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create Customers Table
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Age NUMBER NOT NULL,
    Balance NUMBER(12, 2) DEFAULT 0.00,
    IsVIP VARCHAR2(5) DEFAULT 'FALSE' CHECK (IsVIP IN ('TRUE', 'FALSE'))
);

-- Create Loans Table
CREATE TABLE Loans (
    LoanID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    LoanAmount NUMBER(12, 2) NOT NULL,
    InterestRate NUMBER(4, 2) NOT NULL,
    DueDate DATE NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Insert Sample Data into Customers
INSERT INTO Customers (Name, Age, Balance, IsVIP) VALUES ('John Doe', 65, 12000.00, 'FALSE');
INSERT INTO Customers (Name, Age, Balance, IsVIP) VALUES ('Jane Smith', 45, 8000.00, 'FALSE');
INSERT INTO Customers (Name, Age, Balance, IsVIP) VALUES ('Bob Johnson', 72, 15000.00, 'FALSE');
INSERT INTO Customers (Name, Age, Balance, IsVIP) VALUES ('Alice Brown', 30, 5000.00, 'FALSE');
INSERT INTO Customers (Name, Age, Balance, IsVIP) VALUES ('Charlie Green', 55, 11000.00, 'FALSE');

-- Insert Sample Data into Loans
-- John Doe (CustomerID 1, Age 65) - Loan due in 15 days (Senior, Loan due < 30 days)
INSERT INTO Loans (CustomerID, LoanAmount, InterestRate, DueDate) 
VALUES (1, 5000.00, 8.50, SYSDATE + 15);

-- Jane Smith (CustomerID 2, Age 45) - Loan due in 45 days (Non-senior, Loan due > 30 days)
INSERT INTO Loans (CustomerID, LoanAmount, InterestRate, DueDate) 
VALUES (2, 3000.00, 7.25, SYSDATE + 45);

-- Bob Johnson (CustomerID 3, Age 72) - Loan due in 25 days (Senior, Loan due < 30 days)
INSERT INTO Loans (CustomerID, LoanAmount, InterestRate, DueDate) 
VALUES (3, 10000.00, 9.00, SYSDATE + 25);

-- Alice Brown (CustomerID 4, Age 30) - Loan due in 10 days (Non-senior, Loan due < 30 days)
INSERT INTO Loans (CustomerID, LoanAmount, InterestRate, DueDate) 
VALUES (4, 1500.00, 6.50, SYSDATE + 10);

-- Charlie Green (CustomerID 5, Age 55) - Loan due in 50 days (Non-senior, Loan due > 30 days)
INSERT INTO Loans (CustomerID, LoanAmount, InterestRate, DueDate) 
VALUES (5, 2000.00, 7.80, SYSDATE + 50);

COMMIT;
/
