-- schema.sql
-- Setup schema and dummy data for PL/SQL Stored Procedures exercise

-- Drop existing tables to ensure clean re-runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Employees';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Accounts';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Customers';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create Customers Table
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Age NUMBER NOT NULL
);

-- Create Accounts Table (Savings/Checking accounts for Customers)
CREATE TABLE Accounts (
    AccountID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER,
    AccountType VARCHAR2(20) CHECK (AccountType IN ('Savings', 'Checking')),
    Balance NUMBER(12, 2) DEFAULT 0.00,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Create Employees Table
CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Department VARCHAR2(50) NOT NULL,
    Salary NUMBER(10, 2) NOT NULL
);

-- Insert Sample Data into Customers
INSERT INTO Customers (Name, Age) VALUES ('John Doe', 35);
INSERT INTO Customers (Name, Age) VALUES ('Jane Smith', 45);
INSERT INTO Customers (Name, Age) VALUES ('Bob Johnson', 62);

-- Insert Sample Data into Accounts
-- John Doe (CustomerID 1): one savings, one checking
INSERT INTO Accounts (CustomerID, AccountType, Balance) VALUES (1, 'Savings', 5000.00);
INSERT INTO Accounts (CustomerID, AccountType, Balance) VALUES (1, 'Checking', 1500.00);
-- Jane Smith (CustomerID 2): one savings
INSERT INTO Accounts (CustomerID, AccountType, Balance) VALUES (2, 'Savings', 12000.00);
-- Bob Johnson (CustomerID 3): one checking
INSERT INTO Accounts (CustomerID, AccountType, Balance) VALUES (3, 'Checking', 8000.00);

-- Insert Sample Data into Employees
INSERT INTO Employees (Name, Department, Salary) VALUES ('Alice Green', 'IT', 60000.00);
INSERT INTO Employees (Name, Department, Salary) VALUES ('Charlie Brown', 'HR', 45000.00);
INSERT INTO Employees (Name, Department, Salary) VALUES ('David White', 'IT', 80000.00);
INSERT INTO Employees (Name, Department, Salary) VALUES ('Eva Black', 'Finance', 55000.00);

COMMIT;
/
