# H2 database configurations for local verification
spring.datasource.url=jdbc:h2:mem:springdatajpa;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate configuration for H2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Database initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-h2.sql
